# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('lib_code', models.IntegerField()),
                ('city', models.CharField()),
                ('book', models.ManyToManyField(related_name='books', to='book.booklist')),
            ],
        ),
    ]
