# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_library', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylist',
            name='user',
            field=models.ManyToManyField(related_name='users', to='user.user'),
        ),
    ]
