# Generated by Django 5.2.6 on 2025-09-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('my_library', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='library',
            field=models.ManyToManyField(related_name='lib', to='my_library.librarylist'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='user',
            field=models.ManyToManyField(related_name='my_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='book.category'),
        ),
    ]
