# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pers_id', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('book', models.ManyToManyField(related_name='my_book', to='book.booklist')),
                ('library', models.ManyToManyField(related_name='my_lib', to='my_library.librarylist')),
            ],
        ),
    ]
