# Generated by Django 5.2.6 on 2025-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
        ('my_library', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_book', to='book.booklist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_lib', to='my_library.librarylist'),
        ),
    ]
